raw_data_path: "data/01_raw/Precios_Casas_Boston.csv"
feature_data_path: "data/04_feature/features.csv"
target_column: "medv"
id_column: "ID"

model_path: "data/06_models/model.joblib"
metrics_path: "data/08_reporting/metrics.json"
test_size: 0.2
random_state: 42
